export type NFT = {
  nft_contract_id: string;
  token_id: string;
  market_id: string;
  approval_id: string;
  created_at: Date;
  receipt_id: string;
  kind: string;
  price: string;
  currency: string;
  listed_by: string;
  metadata_id: string;
  reference: string;
  minter: string;
  title: string;
  description: string;
  reference_blob: string;
  media: string;
  extra: null;
  base_uri: string;
  content_flag: null;
  animation_url: null;
};
